# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
ZSH=$HOME/.oh-my-zsh
DEFAULT_USER=$USER

# You can change the theme with another one:

ZSH_THEME="agnoster"

# Useful plugins for Rails development with Sublime Text
source ~/Repos/zsh-autocomplete/zsh-autocomplete.plugin.zsh
plugins=(zsh-autosuggestions git gitfast last-working-dir common-aliases  zsh-syntax-highlighting history-substring-search rails)

# Actually load Oh-My-Zsh
source "${ZSH}/oh-my-zsh.sh"

# Load rbenv
eval "$(rbenv init -)"

# Rails and Ruby uses the local `bin` folder to store binstubs.
# So instead of running `bin/rails` like the doc says, just run `rails`
# Same for `./node_modules/.bin` and nodejs
export PATH="./bin:./node_modules/.bin:${PATH}:/usr/local/sbin"
alias rm='gio trash'

# Store your own aliases in the ~/.aliases file and load the here.
[[ -f "$HOME/.aliases" ]] && source "$HOME/.aliases"

# Encoding stuff for the terminal
export LANG=en_US.UTF-8
export BUNDLER_EDITOR="subl $@ >/dev/null 2>&1"
export BUNDLER_EDITOR="'/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl'"
export BUNDLER_EDITOR="subl $@ >/dev/null 2>&1"


export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
export PATH="$PATH:/opt/mssql-tools/bin"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="/home/cris/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export NODE_OPTIONS=--openssl-legacy-provider

compctl -g '~/.teamocil/*(:t:r)' teamocil
